### PR TITLE
Make fields of signerOptions and verifierOptions optional

### PR DESCRIPTION
**Pull request by rubiin**
jsonwebtoken has all these fields optional, would make sense to make these fields optional here as well

### CODE REVIEW

**Review by simoneb — COMMENTED** [review]
Can you please add a minimal set of tests in this file? https://github.com/nearform/fast-jwt/blob/master/test/types.spec.ts

**Comment by rubiin** [comment]
sure will do

**Comment by simoneb** [comment]
> sure will do

thanks, something minimal really, we don't have many types tests in there but since we're changing the type definitions, we may just as well add some converage.

let me know when you're done and I'll do another review, thanks

**Comment by rubiin** [comment]
I think we dont need tests for the type change as its already covered in these method signature . Here we are using partial which does the same thing https://github.com/nearform/fast-jwt/blob/4ec38d5b80e8583833fcfbafddba689c1ee08158/src/index.d.ts#L145-L148

**Review by simoneb — APPROVED** [review]

**Pull request merged**
