### PR TITLE
fix(typescript): fix typescript type DecodedJwt

### LINKED ISSUE #409: Wrong type for DecodedJwt.payload
DecodedJwt.payload type is string, however should be `any`

### PR DESCRIPTION
**Pull request by qoomon**
fixes #409

### CODE REVIEW

**Review by simoneb — COMMENTED** [review]
can you please add types tests to https://github.com/nearform/fast-jwt/blob/master/test/types.spec.ts?

**Comment by simoneb** [comment]
Please link the issue that this PR fixes, too

**Comment by simoneb** [comment]
I'm not sure why this change would fix your issue. Can you create a test which fails with the existing code, and succeeds with your change?

**Review by simoneb — COMMENTED** [review]
Can you write a test for this?

**Comment by qoomon** [comment]
I changed the pull request to just fix the payload type

**Comment by qoomon** [comment]
I've added a type test for that

**Review by simoneb — APPROVED** [review]

**Comment by simoneb** [comment]
tests are failing, can you take a look please?

**Comment by qoomon** [comment]
lint errors should be fixed

**Pull request merged**
