### PR TITLE
Update `engines.node` to include version 19

### PR DESCRIPTION
**Pull request by arch-mage**

### CODE REVIEW

**Comment by ilteoood** [comment]
Should we consider, instead of this, something like:
>=12.0.0 <20.0.0

@simoneb?

**Comment by ilteoood** [comment]
BTW @arch-mage I would also change the github action workflow, to run some tests even on node 19.

**Comment by simoneb** [comment]
We can even consider dropping 12 since LTS is soon 18 and reduce the matrix a little bit, and yes it makes sense to simplify the engines string to something shorter

**Comment by davidmweber** [comment]
Is it possible to get some progress here? Need to move to node 19. Thanks!

**Comment by marco-ippolito** [comment]
replaced by: https://github.com/nearform/fast-jwt/pull/278

**Pull request closed without merging**
