### PR TITLE
Add a comment for skipped claims check

### PR DESCRIPTION
**Pull request by mcollina**
see also: https://github.com/nearform/fast-jwt/issues/29

### CODE REVIEW

**Comment by panva** [comment]
@mcollina the library is labeled as `JWT` library

> Fast JSON Web Token implementation

JWTs MUST contain top level JSON object payload.

https://tools.ietf.org/html/rfc7519#section-7.2

> 10.  Verify that the resulting octet sequence is a UTF-8-encoded
>     representation of a completely valid JSON object conforming to
>     RFC 7159 [RFC7159]; let the JWT Claims Set be this JSON object.

As a JWT module or non object parsing payloads are to be rejected.

**Comment by mcollina** [comment]
Oh ok! I'll do a more robust fix then.

**Comment by mcollina** [comment]
@panva note that https://jwt.io/ does not complain about payloads being non-objects.

**Comment by panva** [comment]
@mcollina fair enough, do as you like with this module. It's a common mistake made by developers.

**Comment by mcollina** [comment]
I'm going to fix this as it should be spec-complaint and it seems a bug.

**Comment by mcollina** [comment]
(it's just a different PR)

**Pull request closed without merging**
